name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$COMPLETE'
version-resolver:
  default: patch
prerelease: true
filter-by-commitish: true
template: |
  ## Changes

  $CHANGES

  ---

  ## Quick Start
  ### Homebrew
  ```
  brew tap petrinetwork/xco
  brew install xco-blockchain@$MAJOR.$MINOR
  ```

  ### Docker
  ```
  docker run \
    --name xco-blockchain \
    -p 1317:1317 \
    -p 26657:26657 \
    ghcr.io/petrinetwork/xco-blockchain:v$RESOLVED_VERSION \
    start
  ```
#   Release Candidate see changelog
# #dua

##dd