name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$COMPLETE'
version-resolver:
  default: patch
prerelease: true
filter-by-commitish: true
template: |
  ## Quick Start
  ### Homebrew
  ```
  brew tap ixofoundation/ixo-blockchain
  brew install ixo-blockchain
  ```

  ### Docker
  ```
  docker run ghcr.io/ixofoundation/ixo-blockchain:$RESOLVED_VERSION \
    --name ixo-blockchain \
    -p 1317:1317 \
    -p 26657:26657
  ```
#   Release Candidate see changelog
# #dua

##dd