version: "2"
services:
  blockchain:
    container_name: blockchain
    image: trustlab/ixo-blockchain:latest
    restart: always
    ports:
      - "46657:46657"
    logging:
      options:
        max-size: 30m
    
  rest:
    container_name: rest
    image: trustlab/ixo-blockchain-rest:latest
    restart: always
    ports:
      - "1317:1317"
    links:
      - blockchain